In [ ]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

** Here are some high frequency operations you should get used to **

In [ ]:
from __future__ import print_function
import torch

### Construct a 5x3 matrix, uninitialized using [torch.empty]()

In [ ]:
x = torch.empty(5, 3)
print(x)

### Construct a randomly initialized matrix using [torch.rand](https://pytorch.org/docs/stable/torch.html#torch.rand)

Look at the documentation and see if you can make a 10,100 array or random numbers
<details>
<summary>Answer</summary>
<p> torch.rand(10,100)</p></details>


In [ ]:
x = Fill me in
print(x)

### Print out the size of a tensor.  
you will be doing this frequently if developing/debuggin a neural network

In [ ]:
x.size()

### Construct a matrix filled zeros and of dtype floating point 16.  Here is a link to available [types](https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.dtype)

Can you change long to floating point16 below
<details>
<summary>Hint</summary>
<p> torch.zeros(5, 3, dtype=torch.float16) </p></details>



In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

### Element operations

do an element wise add of A and B

In [ ]:
A = torch.rand(5, 3)
B = torch.rand(5, 3)

print(A)
print(B)
print(A + B)

### Alternate method using torch.add

In [ ]:
print(torch.add(A, B))

### Addition: providing an output tensor as argument

In [ ]:
result = torch.empty(5, 3)
torch.add(A, B, out=result)
print(result)

### Addition: in-place



In [ ]:
#### adds x to y
B.add_(A)
print(B)

<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>


### Matrix Multiply


In [29]:
a = torch.randint(4,(2,3))
b = torch.randint(4,(3,2))

In [33]:
# 2x3 @ 3x2 ~ 2x2
a.matmul(b)
torch.matmul(a,b)

tensor([[  8.,  10.],
        [  3.,   8.]])

In [ ]:
### Create a onehot vector


In [40]:

batch_size = 5
nb_digits = 10
# Dummy input that HAS to be 2D for the scatter (you can use view(-1,1) if needed)
y = torch.LongTensor(batch_size,1).random_() % nb_digits
# One hot encoding buffer that you create out of the loop and just keep reusing
y_onehot = torch.FloatTensor(batch_size, nb_digits)

# In your for loop
y_onehot.zero_()
y_onehot.scatter_(1, y, 1)

print(y)
print(y_onehot)

tensor([[ 8],
        [ 1],
        [ 4],
        [ 5],
        [ 7]])
tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.]])


In [ ]:
# Use argmax to grab the index of the highest value

In [53]:
A = torch.rand(3,4,5)
print(A)
A.argmax(dim=0)

tensor([[[ 0.9932,  0.8279,  0.0309,  0.8729,  0.1183],
         [ 0.7757,  0.4410,  0.8362,  0.3319,  0.8460],
         [ 0.6295,  0.2325,  0.8646,  0.5221,  0.7553],
         [ 0.5296,  0.7989,  0.3138,  0.1623,  0.3482]],

        [[ 0.6861,  0.3998,  0.2832,  0.7284,  0.9088],
         [ 0.1722,  0.2103,  0.6787,  0.2517,  0.9082],
         [ 0.9523,  0.1378,  0.0849,  0.1771,  0.7769],
         [ 0.7208,  0.0936,  0.1134,  0.5664,  0.6189]],

        [[ 0.3565,  0.7064,  0.7380,  0.7212,  0.1678],
         [ 0.1144,  0.6004,  0.8036,  0.1378,  0.8147],
         [ 0.6745,  0.6932,  0.1054,  0.3894,  0.9441],
         [ 0.3502,  0.2253,  0.1232,  0.3971,  0.1525]]])


tensor([[ 0,  0,  2,  0,  1],
        [ 0,  2,  0,  0,  1],
        [ 1,  2,  0,  0,  2],
        [ 1,  0,  0,  1,  1]])

### You can use standard NumPy-like indexing with all bells and whistles!

Example Grab the middle column of A (index = 1)

In [41]:
A = torch.rand(3,3)
print(A)
print(A[:, 1])

tensor([[ 0.0591,  0.6838,  0.4621],
        [ 0.7117,  0.8484,  0.3358],
        [ 0.4537,  0.3042,  0.0450]])
tensor([ 0.6838,  0.8484,  0.3042])


### Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

### If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.



NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array


In [ ]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

### See how the numpy array changed in value. 

In [ ]:
a.add_(1)
print(a)
print(b)

Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

### ND Tensors
When working with neural networks, you are always dealing with multidimensional arrays.  Here are some quick tricks
#### Assume A is a 32x32 RGB image


In [8]:
## 3D Tensors
import torch
A = torch.rand(32,32,3)

### Slicing Tensors  - grab 'RED' dimension

In [9]:
red_data = A[:,:,0] #0 represents the first channel of RGB

### Swap the RGB dimension and make the tensor a 3x32x32 tensor

In [11]:
A_rgb_first = A.permute(2,0,1)
print(A_rgb_first.size())

torch.Size([3, 32, 32])


### Add a BatchSize to our Image Tensor
Usually you need to do this to run inference on your trained model

In [20]:
Anew = A.unsqueeze(0)
print(Anew.size())


torch.Size([1, 32, 32, 3])
torch.Size([32, 32, 3])


### Drop the tensor dimension.  

sometimes like in the example above, you might have a tensor with on of the dimensions equal to one.  Use **squeeze()** to drop that dimension>

In [25]:
print(Anew.squeeze(0).size())

torch.Size([32, 32, 3])
